//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class skincare_companionEntities : DbContext
    {
        public skincare_companionEntities()
            : base("name=skincare_companionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INGREDIENT> INGREDIENTs { get; set; }
        public virtual DbSet<OWNERSHIP> OWNERSHIPs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PROGRESSRECORD> PROGRESSRECORDs { get; set; }
        public virtual DbSet<ROUTINE> ROUTINEs { get; set; }
        public virtual DbSet<ROUTINESTEP> ROUTINESTEPs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<v_AllergyWarnings> v_AllergyWarnings { get; set; }
        public virtual DbSet<v_ExpiringInventory> v_ExpiringInventory { get; set; }
        public virtual DbSet<v_RoutineDetail> v_RoutineDetail { get; set; }
    }
}
