//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class skincare_companionEntities1 : DbContext
    {
        public skincare_companionEntities1()
            : base("name=skincare_companionEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLEANSER> CLEANSERs { get; set; }
        public virtual DbSet<INGREDIENT> INGREDIENTs { get; set; }
        public virtual DbSet<MOISTURIZER> MOISTURIZERs { get; set; }
        public virtual DbSet<ROUTINE> ROUTINEs { get; set; }
        public virtual DbSet<SUNSCREEN> SUNSCREENs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<OWNERSHIP> OWNERSHIPs { get; set; }
        public virtual DbSet<PROGRESSRECORD> PROGRESSRECORDs { get; set; }
        public virtual DbSet<ROUTINESTEP> ROUTINESTEPs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
    }
}
