//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOISTURIZER
    {
        public int ID { get; set; }
        public string Texture { get; set; }
        public Nullable<bool> IsNightCream { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
