//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRESSRECORD
    {
        public int LogID { get; set; }
        public int UserID { get; set; }
        public System.DateTime LogDate { get; set; }
        public Nullable<int> SkinRating { get; set; }
        public string Notes { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual User User { get; set; }
    }
}
