//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTINESTEP
    {
        public int ID { get; set; }
        public int RoutineID { get; set; }
        public int StepOrder { get; set; }
        public int ProductID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual ROUTINE ROUTINE { get; set; }
    }
}
