//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROUTINE()
        {
            this.ROUTINESTEPs = new HashSet<ROUTINESTEP>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string RoutineName { get; set; }
        public string RoutineType { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROUTINESTEP> ROUTINESTEPs { get; set; }
    }
}
