//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AllergyWarnings
    {
        public int UserID { get; set; }
        public string Allergies { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string IngredientName { get; set; }
    }
}
